### ISSUE TITLE
F# Creating Types (Records, DUs, Enums, Aliases)

### ISSUE THREAD

**Issue by sheridanchris** [fsharpforyou/fsharpforyou.github.io#4]
Create a chapter/section giving a thorough introduction to the F# type system. 

Points of interest:
* What are records?
* When would you use records?
* How would you create, construct, and modify a record type.
* Anonymous records.
* What are discriminated unions?
* When would you use discriminated unions?
* How would you create, construct, and add values to a discriminated union
* Types abbreviations / Type aliases
* Creating enums
* Using enums
* Enums vs DUs

~It may be of interest... or may be out of this chapter/section's scope~
~* Reference/Value types~

Should there be a mention of record declaration? You can either write them on a single line with a semicolon separator, or on multiple lines.
```fsharp
type Person = { FirstName: string; LastName: string }
type Person' =
    { FirstName: string
      LastName: string }
```

Additionally, there should be a mention of F#'s type inference, and which type it would infer if no type annotation is present
```fsharp
type Person = { FirstName: string; LastName: string }
type Customer =  { FirstName: string; LastName: string }

let christian = { FirstName = "Christian"; LastName = "Sheridan" } // this is a customer.
let christian': Person = { FirstName = "Christian"; LastName = "Sheridan" } // this is a person
```

Any feedback or ideas would be much appreciated!

**Comment by ryanwildes** [comment]
I think you can omit anything regarding reference/value types - given that records and DUs are immutable data types, it's not very relevant.
